name: "Run Tests"

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths: ['Package.swift', 'Sources/**.swift', 'Tests/**.swift', 'Tests/**.js', 'Tests/package.json']

jobs:
  run-tests:
    name: Run Tests on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v1
      - uses: actions/checkout@v3
      - name: Test
        shell: bash
        run: |
          ${{ github.workspace }}/bin/test