name: "Run Tests"

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      [
        "Package.swift",
        "Sources/**.swift",
        "Tests/**.swift",
        "Tests/**.js",
        "Tests/package.json",
        "Tests/package-lock.json",
      ]

jobs:
  swift-format:
    name: Format Swift
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install SwiftFormat
        uses: Cyberbeni/install-swift-tool@v2
        with:
          url: https://github.com/nicklockwood/SwiftFormat
      - name: Run SwiftFormat
        run: swiftformat .
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: botlockwood
          default_author: github_actions
          message: "ran swiftformat"

  run-tests:
    name: Run Tests on ${{ matrix.os }} with Swift ${{ matrix.swift-version }} Node ${{ matrix.node-version }}
    needs: swift-format
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest]
        node-version: ["18.x"]
        swift-version: ["5.7"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: "Tests"
    steps:
      - uses: actions/checkout@v3
      - name: Use Swift ${{ matrix.swift-version }}
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "Tests/package-lock.json"
      - name: Test
        run: "npm install && npm test"
